package:
  name: ruby3.2-concurrent-ruby
  version: 1.2.3
  epoch: 1
  description: Modern concurrency tools including agents, futures, promises, thread pools, actors, supervisors, and more. Inspired by Erlang, Clojure, Go, JavaScript, actors, and classic concurrency patterns.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: concurrent-ruby

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      expected-commit: da6320d22518501abef917f3ac19e9ee9496bffc
      repository: https://github.com/ruby-concurrency/concurrent-ruby.git
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: 001-disable-java.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean

test:
  environment:
    contents:
      packages:
        - wolfi-base
        - build-base
        - ruby3.2-bundler
        - ruby-3.2-dev
  pipeline:
    - uses: git-checkout
      with:
        expected-commit: da6320d22518501abef917f3ac19e9ee9496bffc
        repository: https://github.com/ruby-concurrency/concurrent-ruby.git
        tag: v${{package.version}}
    - runs: |
        bundle
        bundle exec rake compile
        bundle exec rake spec:isolated

update:
  enabled: true
  github:
    identifier: ruby-concurrency/concurrent-ruby
    strip-prefix: v
